
// p4fliconv: high resolution interlaced FLI converter utility
// Copyright (C) 2007-2008 Istvan Varga <istvanv@users.sourceforge.net>
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//
// The Plus/4 program files generated by this utility are not covered by the
// GNU General Public License, and can be used, modified, and distributed
// without any restrictions.

#include "p4fliconv.hpp"
#include "hrbmifli.hpp"

namespace Plus4FLIConv {

  P4FLI_HiResBitmapInterlace::P4FLI_HiResBitmapInterlace()
  {
  }

  P4FLI_HiResBitmapInterlace::~P4FLI_HiResBitmapInterlace()
  {
  }

  bool P4FLI_HiResBitmapInterlace::processImage(
      PRGData& prgData, unsigned int& prgEndAddr, const char *infileName,
      YUVImageConverter& imgConv, Plus4Emu::ConfigurationDB& config)
  {
    (void) infileName;
    (void) imgConv;
    (void) config;
    prgData.setConversionType(2);
    prgData.clear();
    prgData[2] = 0x00;
    prgData[3] = 0x00;
    prgEndAddr = 0x1003U;
    throw Plus4Emu::Exception("FLI with bitmap-only interlace "
                              "is not implemented yet");
  }

}       // namespace Plus4FLIConv

